### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Asad4429** [duolingo/rtl-viewpager#13]
### Version
- 1.0.3
- Every android version & device

### Issue Description:
Issue comes when adding tabs dynamically and notifyDataSetChanged called in adapter
### Step to reproduce:
use FragmentStatePager adapter
1) add one item and call notifyDataSetChanged. (working fine)
2) make an API call and in response to that API call add list of item in pager adapter (Crashed every time)

### Crash log:
java.lang.IndexOutOfBoundsException: Invalid index 15, size is 1
                                                                           at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                           at java.util.ArrayList.set(ArrayList.java:481)
                                                                           at android.support.v4.app.FragmentStatePagerAdapter.destroyItem(FragmentStatePagerAdapter.java:142)
                                                                           at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter.destroyItem(DelegatingPagerAdapter.java:53)
                                                                           at com.duolingo.open.rtlviewpager.RtlViewPager$ReversingAdapter.destroyItem(RtlViewPager.java:275)
                                                                           at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1041)
                                                                           at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3091)
                                                                           at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:290)
                                                                           at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter.superNotifyDataSetChanged(DelegatingPagerAdapter.java:110)
                                                                           at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter$MyDataSetObserver.onChanged(DelegatingPagerAdapter.java:139)
                                                                           at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
                                                                           at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:293)

**Comment by DavidDTA** [comment]
Hello and thank you for the report.

By API call, are you referring to a network request to your server?  Would you be able to create a small demo application that exhibits this crash?

**Comment by hrach** [comment]
Same issue here in production:

> Fatal Exception: java.lang.IndexOutOfBoundsException
> Index: 2, Size: 2

Not able to reproduce manually.

**Comment by manikantagarikipati** [comment]
Yes I'm facing the same issue when `notifyDataSetChanged()` is called, with number of items different from the previous items count

**Comment by avishaigurt-oviva** [comment]
Facing the same issue changing the count manually and calling `notifyDataSetChanged()` in case the device is in RTL (Arabic) and the selected page is the "last" leads to this exception  (in case of LTR works fine):
Stack trace:
```
    java.lang.IndexOutOfBoundsException: Index: 150, Size: 150
        at java.util.ArrayList.set(ArrayList.java:453)
        at android.support.v4.app.FragmentStatePagerAdapter.destroyItem(FragmentStatePagerAdapter.java:142)
        at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter.destroyItem(DelegatingPagerAdapter.java:53)
        at com.duolingo.open.rtlviewpager.RtlViewPager$ReversingAdapter.destroyItem(RtlViewPager.java:275)
        at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1041)
        at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3091)
        at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:289)
        at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter.superNotifyDataSetChanged(DelegatingPagerAdapter.java:110)
        at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter$MyDataSetObserver.onChanged(DelegatingPagerAdapter.java:139)
        at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
        at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:292)
```

Code snippet:
```java
	public void addDay() {
		count++;
		notifyDataSetChanged();
	}
``` 
Android support library version `27.0.2` 
Any ideas?

**Comment by manikantagarikipati** [comment]
Hey , I'd recommend you use recycler view with snap helper as it supports RTL .

**Comment by DavidDTA** [comment]
I will fix this if someone provides a minimal self-contained example app that demonstrates the issue.

**Comment by DavidDTA** [comment]
This library is now deprecated and outstanding issues will not be addressed.  Please use [ViewPager2](https://developer.android.com/training/animation/vp2-migration) instead of this library.
