### ISSUE TITLE
LayoutParams ClassCastException

### ISSUE THREAD

**Issue by flaringapp** [duolingo/rtl-viewpager#16]
Library version 1.0.3
Devices generally on android 4.x

```
Fatal Exception: java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
       at android.widget.ListView.measureScrapChild(ListView.java:1183)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1265)
       at android.widget.ListView.onMeasure(ListView.java:1175)
       at android.view.View.measure(View.java:16514)
       at android.widget.RelativeLayout.measureChild(RelativeLayout.java:689)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:473)
       at android.view.View.measure(View.java:16514)
       at androidx.viewpager.widget.ViewPager.onMeasure(Unknown Source)
       at com.duolingo.open.rtlviewpager.RtlViewPager.onMeasure(Unknown Source)
       at android.view.View.measure(View.java:16514)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16514)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16514)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16514)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.releaseTempRect(Unknown Source)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(Unknown Source)
       at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.layoutDependsOn(Unknown Source)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source)
       at android.view.View.measure(View.java:16514)
       at androidx.drawerlayout.widget.DrawerLayout.onMeasure(Unknown Source)
       at android.view.View.measure(View.java:16514)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source)
       at android.view.View.measure(View.java:16514)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16514)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16514)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16514)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
       at android.view.View.measure(View.java:16514)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5672)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5111)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by DavidDTA** [comment]
Please provided a sample app which demonstrates the issue.  From the stack trace, it looks like something is wrong with items which have been added to a ListView which appears inside of the ViewPager.

**Comment by DavidDTA** [comment]
Closing due to inactivity and lack of details.
