### ISSUE TITLE
IndexOutOfBoundsException in destroyItem on android 7.0 and 7.1 while intializing rtlviewpager

### ISSUE THREAD

**Issue by m7mdyahia** [duolingo/rtl-viewpager#5]
### Required Information

- RtlViewPager Version:
- Android Version and Device : Android 7.1 ,7.0  ,several devices

### Issue Description

I revive this crash report but I didn't test it my self on a device

> java.lang.IndexOutOfBoundsException: 
  at java.util.ArrayList.set(ArrayList.java:427)
  at android.support.v4.app.FragmentStatePagerAdapter.destroyItem(FragmentStatePagerAdapter.java:142)
  at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter.destroyItem(DelegatingPagerAdapter.java:53)
  at com.duolingo.open.rtlviewpager.RtlViewPager$ReversingAdapter.destroyItem(RtlViewPager.java:266)
  at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
  at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
  at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
  at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:2025)
  at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:691)
  at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1806)
  at android.view.View.layout(View.java:18799)
  at android.view.ViewGroup.layout(ViewGroup.java:5952)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
  at android.view.View.layout(View.java:18799)
  at android.view.ViewGroup.layout(ViewGroup.java:5952)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
  at android.view.View.layout(View.java:18799)
  at android.view.ViewGroup.layout(ViewGroup.java:5952)
  at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
  at android.view.View.layout(View.java:18799)
  at android.view.ViewGroup.layout(ViewGroup.java:5952)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
  at android.view.View.layout(View.java:18799)
  at android.view.ViewGroup.layout(ViewGroup.java:5952)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
  at android.view.View.layout(View.java:18799)
  at android.view.ViewGroup.layout(ViewGroup.java:5952)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
  at com.android.internal.policy.DecorView.onLayout(DecorView.java:822)
  at android.view.View.layout(View.java:18799)
  at android.view.ViewGroup.layout(ViewGroup.java:5952)
  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2627)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2343)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1502)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7044)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
  at android.view.Choreographer.doCallbacks(Choreographer.java:702)
  at android.view.Choreographer.doFrame(Choreographer.java:638)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6688)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by DavidDTA** [comment]
Is this on version 1.0.2?

**Comment by m7mdyahia** [comment]
I was using my fork 2926bb6d621067c9e907dca7640e2843

**Comment by m7mdyahia** [comment]
- I am now able to reproduce the crash on emulator 7.0
- I verified that using support view pager doesn't cause crash
- The crash happens on initialization of the view pager

the direct cause is in  android.support.v4.view.ViewPager.populate(ViewPager.java:1236)

I compared this result to running on android 6.0
this line in View pager  shouldn't be reached the outer loop 
> for(int pos = this.mCurItem + 1; pos < N; ++pos)
on Android 7.0 .mCurItem is 0 , on 6 it is the number of pages-1

**Comment by m7mdyahia** [comment]
more investigation:
onRtlPropertiesChanged(int layoutDirection)
is called several times using 1(RTL)

then resolveLayoutDirection() in View class reports decor view of the Activity LTR
and then is called with 0(LTR)

**Comment by wangbin0802** [comment]
Hi, It happened to me when I use 1.0.2, How to solve this issue?

**Comment by m7mdyahia** [comment]
```java
public class RTLOnlyViewPager extends RtlViewPager  {
    public RTLOnlyViewPager(@NonNull Context context) {
        super(context);
    }

    public RTLOnlyViewPager(@NonNull Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    protected boolean isRtl() {
        return true;
    }
}
```

this is just work around

**Comment by DavidDTA** [comment]
I will fix this if someone can provide a minimal self-contained example app which demonstrates the issue.

**Comment by DavidDTA** [comment]
This library is now deprecated and outstanding issues will not be addressed.  Please use [ViewPager2](https://developer.android.com/training/animation/vp2-migration) instead of this library.
